### ISSUE TITLE
kubernetes-external-secrets pod is crash-looping

### ISSUE THREAD

**Issue by chases2** [sebastienvas/istio-testing#3750]
After the cluster update to v1.22, this controller will regularly crash-loop. The cluster version can't be rolled back.

Updating the CRD (https://github.com/istio/test-infra/pull/3749) was not sufficient to resolve this issue.

It is crashing with the following error:
```
TypeError: Cannot read property 'customresourcedefinitions' of undefined
    at CustomResourceManager._createResource (/app/lib/custom-resource-manager.js:30:8)
    at CustomResourceManager._upsertResource (/app/lib/custom-resource-manager.js:87:25)
    at CustomResourceManager.manageCrd (/app/lib/custom-resource-manager.js:117:16)
    at main (/app/bin/daemon.js:37:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by cjwagner** [comment]
Yeah that error doesn't seem very clear/actionable. Maybe we should try upgrading the version of KES. As Chao mentioned, this support seems to have been added at a more recent release version: https://github.com/istio/test-infra/pull/3749/files#r779900937
Maybe there were source code changes involved in addition to the CRD spec change?

**Comment by cjwagner** [comment]
Updating KES fixed this.
/close
